### ISSUE TITLE
Bit explody when the host group doesn't exist

### ISSUE THREAD

**Issue by domcleal** [theforeman/foreman_default_hostgroup#1]
<pre>
undefined method `label' for nil:NilClass (NoMethodError)
/opt/rh/ruby193/root/usr/share/gems/gems/foreman_default_hostgroup-1.0.0/lib/default_hostgroup_managed_host_patch.rb:21:in `importHostAndFacts_with_apply_hostgroup'
/usr/share/foreman/app/controllers/api/v2/hosts_controller.rb:50:in `facts'
</pre>

**Comment by GregSutcliffe** [comment]
@domcleal done! I'll do a 1.0.1 release for you to package tomorrow...
