### ISSUE TITLE
additional settings

### ISSUE THREAD

**Issue by logicminds** [theforeman/foreman_default_hostgroup#13]
Its not obvious where the following additional settings go.  Can you confirm how this works?  This is what I have pieced together.

``` yaml

---
:settings:
  :force_hostgroup_match_only_new: false
:default_hostgroup:
  :facts_map:
    "Default":
      "hostname": ".*"

```

**Comment by GregSutcliffe** [comment]
Settings are in the UI, just look for the Default Hostgroup tab on the Settings page. The rest of the hash looks fine to me, and goes in the config file.

Sorry I didn't reply to the other issue, glad you figured it :)

**Comment by logicminds** [comment]
fixed the docs in my PR
