### ISSUE TITLE
Environnement is not inherit

### ISSUE THREAD

**Issue by darkjeff99** [theforeman/foreman_default_hostgroup#17]
Hello

I use foreman and this plugin, but I have an issue with the environnement inherit.  The host group where the server will be assign have an inherit environnement from parent hostgroup. The hostgroup is apply without issue but the environnement is not apply. 

Before the version 1.10 of foreman I changed the file /usr/share/foreman/vendor/ruby/1.9.1/gems/foreman_default_hostgroup-3.0.0/lib/default_hostgroup_managed_host_patch.rb
 where I change the 
`@host.save(:validate => false)`
by
`@host.save(:validate => true)`

And it was working, but now  with the new version of foreman, it's not working.

Do you have an idea ?

**Comment by GregSutcliffe** [comment]
Sorry for the slow reply. I've not heard of anyone else hitting this, but that doesn't mean it's not real ;)

I'm somewhat swamped at the moment, but I can try to take a look next week and see if I can confirm/deny the issue.

**Comment by rauchrob** [comment]
+1

**Comment by GregSutcliffe** [comment]
Thanks for the reminder @rauchrob. Looking at it, it should be a matter of setting the environment explicitly, which is a one-line patch, but it probably makes sense to add a new setting - not everyone will want to force-inherit the Hostgroup's environment (eg for existing hosts where only_new == false).

I'll have a think about the right combination of settings and then do a new release sometime soon.

**Comment by darkjeff99** [comment]
Good news. 

Today I have to fix the env for each hostgroup.  

Thx I'm waiting the new release

**Comment by GregSutcliffe** [comment]
This is fixed in v4 of the plugin which will be available for Foreman 1.12 - thanks for reporting guys!
