### ISSUE TITLE
wrong number of arguments

### ISSUE THREAD

**Issue by Reamer** [theforeman/foreman_default_hostgroup#3]
Hi,
I have a fresh foreman Version 1.3.2 and a problem. Maybe you have an idea why this plugin doesn't work.

http://paste2.org/vZIU7tb9

Thanks in advance for your help

**Comment by GregSutcliffe** [comment]
Looks like you're trying to use the master-branch against stable foreman - try using the 1.0.1 gem release.

**Comment by Reamer** [comment]
You are right, thanks for the fast answer.
