### ISSUE TITLE
Upgrade to 1.16 issues -> tfm-rubygem-foreman_default_hostgroup.noarch

### ISSUE THREAD

**Issue by y-me-y** [theforeman/foreman_default_hostgroup#32]
I removed the above gem and the below error went away. 

no implicit conversion of nil into String (TypeError)
  /usr/share/foreman/config/initializers/assets.rb:73:in `join'
  /usr/share/foreman/config/initializers/assets.rb:73:in `block (4 levels) in <top (required)>'
  /usr/share/foreman/config/initializers/assets.rb:72:in `map'
  /usr/share/foreman/config/initializers/assets.rb:72:in `block (3 levels) in <top (required)>'
  /usr/share/foreman/config/initializers/assets.rb:69:in `each'
  /usr/share/foreman/config/initializers/assets.rb:69:in `block (2 levels) in <top (required)>'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:36:in `call'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `instance_exec'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `run'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:226:in `block in tsort_each'
  /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:429:in `each_strongly_connected_component_from'
  /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:347:in `block in each_strongly_connected_component'
  /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:345:in `each'
  /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:345:in `call'
  /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:345:in `each_strongly_connected_component'
  /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:224:in `tsort_each'
  /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:203:in `tsort_each'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/initializable.rb:54:in `run_initializers'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/application.rb:352:in `initialize!'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/railtie.rb:194:in `public_send'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/railtie.rb:194:in `method_missing'
  /usr/share/foreman/config/environment.rb:5:in `<top (required)>'
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
  config.ru:3:in `block in <main>'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/rack-1.6.2/lib/rack/builder.rb:55:in `instance_eval'
  /opt/rh/sclo-ror42/root/usr/share/gems/gems/rack-1.6.2/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:112:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:112:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'

**Comment by juaorteg** [comment]
I have this same issue. Installed Foreman 1.16 and the plugin:

$ foreman-installer -v --enable-foreman-plugin-default-hostgroup

When I restart Foreman I receive:
/usr/share/foreman/config/initializers/assets.rb:73:in `join': no implicit conversion of nil into String (TypeError)

**Comment by mmoll** [comment]
GH-31 & GH-33

**Comment by juaorteg** [comment]
Thanks! Its working now.

**Comment by ekohl** [comment]
Since this is part of 4.0.1 I think it can be closed. It still needs to be included in 1.16 RPMs though.

**Comment by mmoll** [comment]
https://github.com/theforeman/foreman-packaging/pull/2082

**Comment by ekohl** [comment]
Looks like it's on me then. I'll take a look

**Comment by jmp242** [comment]
Shouldn't the support table be updated with 4.0.1 for 1.16 and newer?

**Comment by mmoll** [comment]
I'm pretty sure, 1.17+ is broken again :)

**Comment by GregSutcliffe** [comment]
Table updated in https://github.com/theforeman/foreman_default_hostgroup/commit/36fa29c78a717c50d8fb2e8da709b4063ad74d88#diff-04c6e90faac2675aa89e2176d2eec7d8R21 :)
