### ISSUE TITLE
Plugin doesn't work with Foreman 1.17RC2

### ISSUE THREAD

**Issue by Sebor** [theforeman/foreman_default_hostgroup#35]
My environment:
CentOS 7.4

Plugin was installed via foreman-installer:
\# foreman-installer --enable-foreman-plugin-default-hostgroup

Packages:
tfm-rubygem-foreman_ansible_core-2.0.2-1.fm1_17.el7.noarch
foreman-release-1.17.0-0.3.RC2.el7.noarch
tfm-rubygem-foreman_remote_execution_core-1.1.0-1.fm1_17.el7.noarch
foreman-1.17.0-0.3.RC2.el7.noarch
foreman-proxy-1.17.0-0.1.RC2.el7.noarch
foreman-cli-1.17.0-0.3.RC2.el7.noarch
tfm-rubygem-foreman-tasks-0.11.2-1.fm1_17.el7.noarch
tfm-rubygem-foreman_default_hostgroup-4.0.1-1.fm1_17.el7.noarch
foreman-release-scl-4-1.el7.noarch
foreman-postgresql-1.17.0-0.3.RC2.el7.noarch
tfm-rubygem-hammer_cli_foreman-0.12.0-2.el7.noarch
tfm-rubygem-foreman_ansible-2.0.1-1.fm1_17.el7.noarch
foreman-openstack-1.17.0-0.3.RC2.el7.noarch
foreman-selinux-1.17.0-0.1.RC2.el7.noarch
foreman-installer-1.17.0-0.1.RC2.el7.noarch
tfm-rubygem-foreman-tasks-core-0.2.4-1.fm1_17.el7.noarch
tfm-rubygem-foreman_remote_execution-1.4.5-2.fm1_17.el7.noarch
foreman-debug-1.17.0-0.3.RC2.el7.noarch

Plugin config(/etc/foreman/plugins/foreman_default_hostgroup.yaml):
`---
:default_hostgroup:
  :facts_map:
    "all-servers":
      "hostname": ".*"
`

Plugin config (WebUI):
force_host_environment 	Yes
force_hostgroup_match_only_new 	Yes
force_hostgroup_match 	No

Autosign rule:
*.domain.com

So, when I add host in foreman (I just run puppet agent -t) I see host in foreman host list but without any assigned hostgroup.

In foreman log (/var/log/foreman/production.log) there are following lines:
2018-04-04 14:00:09  [app] [W] ForemanDefaultHostgroup: skipping engine hook (undefined method `alias_method_chain' for #<Class:0x0000000d351558>
 | Did you mean?  alias_method)
2018-04-04 14:00:10  [app] [W] ForemanDefaultHostgroup: skipping engine hook (undefined method `alias_method_chain' for #<Class:0x0000000c041878>
 | Did you mean?  alias_method)

How can I resolve it?

**Comment by mmoll** [comment]
@GregSutcliffe any plans to make this plugin 1.17+ compatible?

**Comment by dgoetz** [comment]
It seems this plugin is another one were alias_method_chain should be replaced like stated in https://github.com/theforeman/foreman_monitoring/issues/30.

**Comment by mmoll** [comment]
there are quite some more issues left then ;)

**Comment by dasmall80** [comment]
Submitted PR #36 with a possible fix.

**Comment by lucasdiedrich** [comment]
This behavior persist on Foreman 1.17 (Final).

**Comment by GregSutcliffe** [comment]
Thanks for the patience guys, been away a while. Reviewing your patch now @lucasdiedrich - thanks!

Ugh, can't read, I meant @dasmall80 clearly!

**Comment by ivanobom** [comment]
How do I apply this patch?

**Comment by lucasdiedrich** [comment]
@ivanobom , in my case i just replaced the class used in [PR 36](https://github.com/theforeman/foreman_default_hostgroup/pull/36/commits/71be219ccd354fef971e8e2ed8c5b813ec7fec99) and everything is working fine now.

**Comment by ivanobom** [comment]
Indeed @lucasdiedrich, I just replaced the existing file (default_hostgroup_base_host_patch.rb) by the new one and everything is working fine now. Thanks!

**Comment by GregSutcliffe** [comment]
#37 is merged, new gem/package releases are being prepared today. Thanks again for the patience...
