### ISSUE TITLE
Failure in migration step with Foreman 3.7 when run with foreman-installer after initial installation

### ISSUE THREAD

**Issue by JohnCasey** [theforeman/foreman_default_hostgroup#59]
When activating the plugin after the initial foreman installation, the rake tasks abort with the message in the log file:
```
column 'settings.category' does not exist
```
According to https://github.com/theforeman/foreman/pull/9524 there was a change introduced with foreman 3.7 to drop this column.

Please update the migration to support foreman 3.7, maybe changing the migration to the following as mentioned in the linked post above is sufficient:
```
Setting.where(category: 'Setting::Plugin').update_all(category: 'Setting') if column_exists?(:settings, :category)
```

**Comment by this-tech** [comment]
I just did this on my machine and it does resolve the issue.

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman_default_hostgroup/pull/64 is merged
